### ISSUE TITLE
Export crossDomainFetch by default

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-fetch-jsonp#2]
It feels like the wrong emphasis to export jsonp by default and crossDomainFetch as a property. jsonp is a hack we should be getting rid of eventually.

Can we consider killing this component - before it gets widely adopted - and releasing o-fetch-cors which exports jsonp as a property, but crossDomainFetch as default? @AlbertoElias

**Comment by ironsidevsquincy** [comment]
The assumption then is every endpoint has a jsonp response, which I don't think is correct. Personally I think jsonp is a valid, which can be used by clients if they choose, and therefore they should 'opt in' by using this module

**Comment by wheresrhys** [comment]
but all this repo does is provide fetch with a jsonp polyfill/fallback. Why woudl anyone use it unlesss communicating with a jsonp enabled endpoint?

**Comment by wheresrhys** [comment]
When the endpoint doesn't support jsonp you'd just use fetch

**Comment by ironsidevsquincy** [comment]
So you basically just want to change the name to `o-fetch-cors`? I guess that's fine as long as it's well flagged that any endpoint needs a jsonp response

**Comment by AlbertoElias** [comment]
Why do we need to rename the module? As soon as we don't need jsonp, we can
just use native fetch everywhere, right? Or would a CORS enabled fetch
helper be useful?

On Tue, 24 May 2016 at 11:52 Darren Hurley <notifications@github.com> wrote:

> So you basically just want to change the name to o-fetch-cors? I guess
> that's fine as long as it's well flagged that any endpoint needs a jsonp
> response
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-fetch-jsonp/issues/2#issuecomment-221233942>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by wheresrhys** [comment]
renaming was just a suggestion to avoid a major release

On 24 May 2016 at 12:01, Alberto Elias <notifications@github.com> wrote:

> Why do we need to rename the module? As soon as we don't need jsonp, we can
> just use native fetch everywhere, right? Or would a CORS enabled fetch
> helper be useful?
>
> On Tue, 24 May 2016 at 11:52 Darren Hurley <notifications@github.com>
> wrote:
>
> > So you basically just want to change the name to o-fetch-cors? I guess
> > that's fine as long as it's well flagged that any endpoint needs a jsonp
> > response
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Financial-Times/o-fetch-jsonp/issues/2#issuecomment-221233942
> >
> >
>
> --
>
> ------------------------------
>
> *This email was sent by a company owned by Financial Times Group Limited
> ("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"),
>
> registered office at Number One Southwark Bridge, London SE1 9HL.
> Registered in England and Wales with company number 879531. This e-mail
> may
> contain confidential information. If you are not the intended recipient,
> please notify the sender immediately, delete all copies and do not
> distribute it further. It could also contain personal views which are not
> necessarily those of the FT Group. We may monitor outgoing or
> incoming emails as permitted by law.*
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-fetch-jsonp/issues/2#issuecomment-221235871>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by AlbertoElias** [comment]
I think we should do a major release, renaming and deprecating modules is worse of a hassle

**Comment by wheresrhys** [comment]
I don't think it matters much either way this time so do which you prefer

On 24 May 2016 at 12:17, Alberto Elias <notifications@github.com> wrote:

> I think we should do a major release, renaming and deprecating modules is
> worse of a hassle
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-fetch-jsonp/issues/2#issuecomment-221239014>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by AlbertoElias** [comment]
As soon as we can merge your pr, I'll merge this one

**Comment by wheresrhys** [comment]
I don't really like my PR. I may submit a different solution. In the meantime it's not urgent - I managed to fix by adding a namespace to n-jsonp
